### ISSUE TITLE
Need help building - VS2015

### ISSUE THREAD

**Issue by vnl** [plstcharles/meta-licensor#2]
Hello,
Was wondering if I get any help in building the project. 

1. Clone from git - Open VSTools Cmd and navigate to the project
2. mkdir build
3. cd build
4. cmake -G "Visual Studio 15 2017" ..

This does not build and gives me an error saying the configuration failed.

**Comment by plstcharles** [comment]
Hello!

The projects all have a dependency on boost; make sure boost is installed on your system, and make sure CMake finds it. Minimally, you will need to set boost_DIR, and boost_INCLUDE_DIR to proper paths so that CMake can find the headers and required modules (date_time, filesystem, program_options, system, unit_test).

I'm assuming that's your problem, as you didn't post the configuration log here, and that's the only potential issue I can see on my side.
